<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * One-click LTI registration page for EduGears AI.
 *
 * Creates the LTI 1.3 tool locally in Moodle using internal APIs,
 * then registers the platform with EduGears via the admin's browser
 * (bypassing server-side firewalls).
 *
 * @package    local_edugears
 * @copyright  2026 EduGears AI <support@edugears.ai>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

require_once(__DIR__ . '/../../config.php');
require_once($CFG->dirroot . '/mod/lti/locallib.php');

require_login();
require_capability('moodle/site:config', context_system::instance());

$PAGE->set_context(context_system::instance());
$PAGE->set_url(new moodle_url('/local/edugears/register.php'));
$PAGE->set_title(get_string('register_title', 'local_edugears'));
$PAGE->set_heading(get_string('register_title', 'local_edugears'));

$apibase = 'https://lti-api.edugears.ai';
$portal  = 'https://lti.edugears.ai';

// Handle POST — create the LTI tool.

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    require_sesskey();

    // Check if EduGears tool already exists.
    $existing = $DB->get_record_select(
        'lti_types',
        $DB->sql_like('baseurl', ':url'),
        ['url' => '%lti-api.edugears.ai%']
    );

    if ($existing) {
        $typeid = $existing->id;
        $clientid = $existing->clientid;
        $isnewtool = false;
    } else {
        // Create the LTI 1.3 tool type using Moodle's internal API.
        $type = new stdClass();
        $type->state = LTI_TOOL_STATE_CONFIGURED;
        $type->name = 'EduGears AI';
        $type->baseurl = $apibase . '/lti/launch';
        $type->tooldomain = 'lti-api.edugears.ai';
        $type->ltiversion = LTI_VERSION_1P3;
        $type->description = 'AI-powered learning tools for education';
        $type->clientid = null; // Auto-generated by Moodle.
        $type->course = SITEID;

        $config = new stdClass();
        $config->lti_publickeyset     = $apibase . '/lti/jwks';
        $config->lti_keytype          = 'JWK_KEYSET';
        $config->lti_initiatelogin    = $apibase . '/lti/login';
        $config->lti_redirectionuris  = $apibase . '/lti/launch';
        $config->lti_icon              = $apibase . '/logo.png';
        $config->lti_secureicon        = $apibase . '/logo.png';
        $config->lti_customparameters = '';
        $config->lti_coursevisible     = LTI_COURSEVISIBLE_ACTIVITYCHOOSER;
        $config->lti_launchcontainer   = LTI_LAUNCH_CONTAINER_DEFAULT;
        $config->lti_sendname          = LTI_SETTING_ALWAYS;
        $config->lti_sendemailaddr     = LTI_SETTING_ALWAYS;
        $config->lti_acceptgrades      = LTI_SETTING_DELEGATE;
        $config->lti_contentitem       = 1; // Enable deep linking.
        $config->ltiservice_gradesynchronization = 2;
        $config->ltiservice_memberships = 1;

        $typeid = lti_add_type($type, $config);
        $isnewtool = true;

        // Read back the auto-generated client ID.
        $tool = $DB->get_record('lti_types', ['id' => $typeid], 'clientid');
        $clientid = $tool->clientid;
    }

    // Build the registration bundle for EduGears.
    $bundle = [
        'issuer'         => $CFG->wwwroot,
        'client_id'      => $clientid,
        'platform_name'  => $SITE->fullname,
        'auth_login_url' => $CFG->wwwroot . '/mod/lti/auth.php',
        'auth_token_url' => $CFG->wwwroot . '/mod/lti/token.php',
        'key_set_url'    => $CFG->wwwroot . '/mod/lti/certs.php',
        'deployment_ids' => [(string) $typeid],
    ];

    $bundlejson = json_encode($bundle, JSON_UNESCAPED_SLASHES);
    $bundleb64  = base64_encode($bundlejson);

    // Render success page with JS that registers with EduGears.
    echo $OUTPUT->header();
    // Page heading is already rendered by $PAGE->set_heading().

    // Status area — JS will update this.
    echo '<div id="eg-status" style="max-width:640px; margin:20px auto; padding:24px;
            background:#f0fdf4; border:1px solid #bbf7d0; border-radius:8px;">
        <h3 style="margin:0 0 8px; color:#166534;">' .
        ($isnewtool
            ? get_string('register_success', 'local_edugears')
            : get_string('register_already_exists', 'local_edugears'))
        . '</h3>
        <p style="margin:0 0 16px; color:#334155;">
            ' . get_string('register_cloud_pending', 'local_edugears') . '
        </p>
        <div id="eg-result" style="text-align:center; padding:16px;">
            <div style="display:inline-block; width:24px; height:24px; border:3px solid #059669;
                        border-top-color:transparent; border-radius:50%;
                        animation: egspin 0.8s linear infinite;"></div>
            <p style="color:#64748b; margin:8px 0 0; font-size:14px;">Connecting to EduGears...</p>
        </div>
    </div>
    <style>@keyframes egspin { to { transform: rotate(360deg); } }</style>';

    // Fallback area — hidden by default, shown if JS fetch fails.
    echo '<div id="eg-fallback" style="display:none; max-width:640px; margin:20px auto; padding:24px;
            background:#fffbeb; border:1px solid #fde68a; border-radius:8px;">
        <h3 style="margin:0 0 8px; color:#92400e;">' .
            get_string('register_cloud_fail', 'local_edugears') . '</h3>
        <p style="margin:0 0 12px; color:#334155;">' .
            get_string('register_manual_steps', 'local_edugears') . '</p>
        <label style="font-weight:600; display:block; margin-bottom:4px;">' .
            get_string('register_bundle_label', 'local_edugears') . '</label>
        <div style="position:relative;">
            <textarea id="eg-bundle" rows="3" readonly
                style="width:100%; font-family:monospace; font-size:12px; padding:8px;
                       border:1px solid #d1d5db; border-radius:4px; resize:none;">' .
                s($bundleb64) . '</textarea>
            <button type="button" onclick="
                document.getElementById(\'eg-bundle\').select();
                document.execCommand(\'copy\');
                this.textContent=\'Copied!\';
                setTimeout(()=>this.textContent=\'Copy\',2000);
            " style="position:absolute; top:4px; right:4px; padding:4px 12px;
                     background:#f59e0b; color:#fff; border:none; border-radius:4px;
                     cursor:pointer; font-size:12px;">Copy</button>
        </div>
        <p style="margin:12px 0 0; font-size:14px; color:#64748b;">
            ' . get_string('register_manual_link', 'local_edugears') . '
            <a href="' . $portal . '/portal/register-manual" target="_blank"
               style="color:#2563eb; text-decoration:underline;">' .
                $portal . '/portal/register-manual</a>
        </p>
    </div>';

    // JavaScript: send bundle to EduGears from the admin's browser.
    echo '<script>
    (function() {
        var bundle = ' . $bundlejson . ';
        var apiUrl = ' . json_encode($apibase . '/api/plugin/register') . ';

        fetch(apiUrl, {
            method: "POST",
            headers: {"Content-Type": "application/json"},
            body: JSON.stringify(bundle)
        })
        .then(function(resp) {
            if (!resp.ok) throw new Error("HTTP " + resp.status);
            return resp.json();
        })
        .then(function(data) {
            var resultEl = document.getElementById("eg-result");
            resultEl.innerHTML = ""
                + "<div style=\"background:#ecfdf5; border:2px solid #059669;"
                + " border-radius:8px; padding:16px; text-align:center;\">"
                + "  <p style=\"margin:0 0 8px; font-size:14px; color:#334155;\">Your claim code:</p>"
                + "  <p style=\"margin:0; font-size:28px; font-weight:700; color:#059669; letter-spacing:2px;\">"
                +        data.claim_code
                + "  </p>"
                + "  <p style=\"margin:12px 0 0; font-size:13px; color:#64748b;\">"
                + "    Save this code — you will need it later to link your billing account."
                + "  </p>"
                + "</div>";
        })
        .catch(function(err) {
            console.warn("EduGears registration failed:", err);
            document.getElementById("eg-result").innerHTML =
                "<p style=\"color:#dc2626;\">Could not reach EduGears server.</p>";
            document.getElementById("eg-fallback").style.display = "block";
        });
    })();
    </script>';

    echo $OUTPUT->footer();
    exit;
}

// GET — show confirmation page.

echo $OUTPUT->header();
// Page heading is already rendered by $PAGE->set_heading().

// Check if already registered.
$existing = $DB->get_record_select(
    'lti_types',
    $DB->sql_like('baseurl', ':url'),
    ['url' => '%lti-api.edugears.ai%']
);

echo '<div style="max-width:640px; margin:20px auto;">';

if ($existing) {
    echo '<div style="padding:12px 16px; background:#eff6ff; border:1px solid #bfdbfe;
                border-radius:8px; margin-bottom:20px; color:#1e40af;">
        ' . get_string('register_already_exists', 'local_edugears') . '
    </div>';
}

echo '<div style="padding:24px; background:#fff; border:1px solid #e2e8f0; border-radius:8px;">
    <p style="margin:0 0 16px; color:#334155; font-size:15px; line-height:1.6;">'
        . get_string('register_confirm', 'local_edugears') .
    '</p>
    <form method="post" action="' . (new moodle_url('/local/edugears/register.php'))->out() . '">
        <input type="hidden" name="sesskey" value="' . sesskey() . '">
        <button type="submit" class="btn btn-primary" style="font-size:16px; padding:10px 32px;">
            ' . get_string('register_button', 'local_edugears') . '
        </button>
    </form>
</div>';

echo '</div>';
echo $OUTPUT->footer();
